version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "StefanGreve"
    reviewers:
      - "StefanGreve"
    labels:
      - "dependencies"
