coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
  ignore:
    - "setup.py"
    - "src/anonpy/__init__.py"
    - "src/anonpy/**/__init__.py"
    - "src/anonpy/providers/*.py"
    - "tests/*.py"
