name: Test Coverage
on: [ push ]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: "3.12"
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: "3.12"
    - name: Generate a new Code Coverage Report
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
        pip install pytest-cov
        pip install -e .
        pytest --cov=./ --cov-report=xml
    - name: Upload results to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        verbose: true
