name: PyPI Release

on:
  workflow_dispatch:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "!*-rc.[0-9]+"

jobs:
  deploy:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ '3.12' ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Development Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/development.txt
        pip install -e .
    - name: Build and Publish to https://pypi.org/project/anonypy/
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        # builds both sdist and wheel
        python -m build --no-isolation
        twine upload dist/**
